import React, { createContext, useContext, useState, useEffect } from 'react'

const LangContext = createContext()

const traducciones = {
    es: {
        productos: 'Productos',
        tendencias: 'Tendencias',
        outfits: 'Outfits',
        ruleta: 'Ruleta',
        login: 'Login',
        registro: 'Registro',
        salir: 'Salir',
        panel: 'Panel',
        coleccion: 'COLECCIÓN',
        buscar: 'Buscar productos...',
        todos: 'Todos',
        cargando: 'CARGANDO...',
        noHayProductos: 'NO HAY PRODUCTOS',
        añadirCarrito: 'Añadir al Carrito',
        talla: 'Talla',
        descripcion: 'Descripción',
        resenas: 'RESEÑAS',
        escribirResena: 'ESCRIBIR RESEÑA',
        puntuacion: 'Puntuación',
        titulo: 'Título de tu reseña',
        comentario: 'Cuéntanos tu experiencia...',
        enviarResena: 'Enviar Reseña',
        enviando: 'Enviando...',
        añadidoCarrito: '✓ Añadido al carrito',
        añadidoDeseos: '✓ Añadido a tu lista de deseos',
        volver: '← Volver',
        carrito: 'CARRITO',
        tuSeleccion: 'Tu selección',
        resumen: 'Resumen',
        subtotal: 'Subtotal',
        envio: 'Envío',
        gratis: 'Gratis',
        total: 'Total',
        finalizarPedido: 'Finalizar Pedido',
        seguirComprando: 'Seguir comprando',
        carritoVacio: 'Tu carrito está vacío',
        verProductos: 'Ver productos',
        pedidoRealizado: 'PEDIDO REALIZADO',
        graciasCompra: 'Gracias por tu compra. Te avisaremos cuando tu pedido esté en camino.',
        cupon: 'Cupón de descuento',
        aplicar: 'Aplicar',
        fashionFlow: 'Fashion Flow Passion',
        shopNow: 'Shop Now',
        tendenciasTitle: 'TENDENCIAS',
        loMasPopular: 'Lo más popular',
        generadorOutfits: 'GENERADOR DE OUTFITS',
        estiloPersonalizado: 'Estilo personalizado',
        generarOutfit: '✦ Generar Outfit',
        generando: 'Generando...',
        tuOutfit: 'Tu outfit de hoy',
        totalOutfit: 'Total del outfit',
        ruletaTitle: 'RULETA DE DESCUENTOS',
        girarRuleta: '¡Girar Ruleta!',
        girando: 'Girando...',
        giraYGana: 'Gira y gana',
        felicidades: '¡Felicidades!',
        usaCodigo: 'Usa este código en tu próxima compra',
        copiar: 'Copiar',
        copiado: '✓ Copiado',
        sinSuerte: 'Sin suerte esta vez',
        volverMes: 'Vuelve el mes que viene',
        miCuenta: 'Mi cuenta',
        misPedidos: 'Mis Pedidos',
        listaDeseos: 'Lista de Deseos',
        misResenas: 'Mis Reseñas',
        devoluciones: 'Devoluciones',
    },
    en: {
        productos: 'Products',
        tendencias: 'Trends',
        outfits: 'Outfits',
        ruleta: 'Wheel',
        login: 'Login',
        registro: 'Sign Up',
        salir: 'Logout',
        panel: 'Panel',
        coleccion: 'COLLECTION',
        buscar: 'Search products...',
        todos: 'All',
        cargando: 'LOADING...',
        noHayProductos: 'NO PRODUCTS',
        añadirCarrito: 'Add to Cart',
        talla: 'Size',
        descripcion: 'Description',
        resenas: 'REVIEWS',
        escribirResena: 'WRITE A REVIEW',
        puntuacion: 'Rating',
        titulo: 'Review title',
        comentario: 'Tell us about your experience...',
        enviarResena: 'Submit Review',
        enviando: 'Sending...',
        añadidoCarrito: '✓ Added to cart',
        añadidoDeseos: '✓ Added to wishlist',
        volver: '← Back',
        carrito: 'CART',
        tuSeleccion: 'Your selection',
        resumen: 'Summary',
        subtotal: 'Subtotal',
        envio: 'Shipping',
        gratis: 'Free',
        total: 'Total',
        finalizarPedido: 'Checkout',
        seguirComprando: 'Continue shopping',
        carritoVacio: 'Your cart is empty',
        verProductos: 'View products',
        pedidoRealizado: 'ORDER PLACED',
        graciasCompra: 'Thank you for your purchase. We will notify you when your order is on its way.',
        cupon: 'Discount coupon',
        aplicar: 'Apply',
        fashionFlow: 'Fashion Flow Passion',
        shopNow: 'Shop Now',
        tendenciasTitle: 'TRENDS',
        loMasPopular: 'Most popular',
        generadorOutfits: 'OUTFIT GENERATOR',
        estiloPersonalizado: 'Personalized style',
        generarOutfit: '✦ Generate Outfit',
        generando: 'Generating...',
        tuOutfit: 'Your outfit today',
        totalOutfit: 'Outfit total',
        ruletaTitle: 'DISCOUNT WHEEL',
        girarRuleta: 'Spin the Wheel!',
        girando: 'Spinning...',
        giraYGana: 'Spin and win',
        felicidades: 'Congratulations!',
        usaCodigo: 'Use this code on your next purchase',
        copiar: 'Copy',
        copiado: '✓ Copied',
        sinSuerte: 'Better luck next time',
        volverMes: 'Come back next month',
        miCuenta: 'My account',
        misPedidos: 'My Orders',
        listaDeseos: 'Wishlist',
        misResenas: 'My Reviews',
        devoluciones: 'Returns',
    },
    fr: {
        productos: 'Produits',
        tendencias: 'Tendances',
        outfits: 'Tenues',
        ruleta: 'Roue',
        login: 'Connexion',
        registro: 'S\'inscrire',
        salir: 'Déconnexion',
        panel: 'Panneau',
        coleccion: 'COLLECTION',
        buscar: 'Rechercher des produits...',
        todos: 'Tous',
        cargando: 'CHARGEMENT...',
        noHayProductos: 'PAS DE PRODUITS',
        añadirCarrito: 'Ajouter au panier',
        talla: 'Taille',
        descripcion: 'Description',
        resenas: 'AVIS',
        escribirResena: 'ÉCRIRE UN AVIS',
        puntuacion: 'Note',
        titulo: 'Titre de votre avis',
        comentario: 'Parlez-nous de votre expérience...',
        enviarResena: 'Envoyer l\'avis',
        enviando: 'Envoi...',
        añadidoCarrito: '✓ Ajouté au panier',
        añadidoDeseos: '✓ Ajouté à la liste de souhaits',
        volver: '← Retour',
        carrito: 'PANIER',
        tuSeleccion: 'Votre sélection',
        resumen: 'Résumé',
        subtotal: 'Sous-total',
        envio: 'Livraison',
        gratis: 'Gratuite',
        total: 'Total',
        finalizarPedido: 'Commander',
        seguirComprando: 'Continuer les achats',
        carritoVacio: 'Votre panier est vide',
        verProductos: 'Voir les produits',
        pedidoRealizado: 'COMMANDE PASSÉE',
        graciasCompra: 'Merci pour votre achat. Nous vous informerons quand votre commande est en route.',
        cupon: 'Coupon de réduction',
        aplicar: 'Appliquer',
        fashionFlow: 'Fashion Flow Passion',
        shopNow: 'Acheter',
        tendenciasTitle: 'TENDANCES',
        loMasPopular: 'Le plus populaire',
        generadorOutfits: 'GÉNÉRATEUR DE TENUES',
        estiloPersonalizado: 'Style personnalisé',
        generarOutfit: '✦ Générer une tenue',
        generando: 'Génération...',
        tuOutfit: 'Votre tenue du jour',
        totalOutfit: 'Total tenue',
        ruletaTitle: 'ROUE DES RÉDUCTIONS',
        girarRuleta: 'Tourner la roue!',
        girando: 'Rotation...',
        giraYGana: 'Tournez et gagnez',
        felicidades: 'Félicitations!',
        usaCodigo: 'Utilisez ce code pour votre prochain achat',
        copiar: 'Copier',
        copiado: '✓ Copié',
        sinSuerte: 'Pas de chance cette fois',
        volverMes: 'Revenez le mois prochain',
        miCuenta: 'Mon compte',
        misPedidos: 'Mes commandes',
        listaDeseos: 'Liste de souhaits',
        misResenas: 'Mes avis',
        devoluciones: 'Retours',
    }
}

export function LangProvider({ children }) {
    const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'es')

    useEffect(() => {
        localStorage.setItem('lang', lang)
    }, [lang])

    const t = traducciones[lang]

    return (
        <LangContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LangContext.Provider>
    )
}

export function useLang() {
    return useContext(LangContext)
}